name: artefakty
version: '1.0-SNAPSHOT'
main: com.jakub.artefakty.Artefakty
api-version: '1.19'
commands:
  trofeum:
    description: Otwiera ekwipunek z trofeami.
  trofea:
    description: Otwiera ekwipunek z trofeami.