name: artefakty
version: '1.0-SNAPSHOT'
main: com.jakub.artefakty.Artefakty
api-version: '1.19'
commands:
  trofeum:
    description: Otwiera ekwipunek trofeów.
  trofea:
    description: Otwiera ekwipunek trofeów.
#  trofea admin clear:
#    description: Usuwa określony przedmiot z ekwipunku trofeów.